// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ltnjdpteckpdodwuegfw.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imx0bmpkcHRlY2twZG9kd3VlZ2Z3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY2NTcwMDQsImV4cCI6MjA3MjIzMzAwNH0.95qwJnD__cfCIf5Y8KRBepU2jYWBhFafeNEuKxoyULk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});